### ISSUE TITLE
CSP errors on denolandia.cdaringe.com

### ISSUE THREAD

**Issue by leonardodino** [dino-dna/denolandia#2]
Hey there! (:
thanks for this awesome project.

I'm just having issues on the deployed version, the error seems prevent the search function from working.

As [noted](https://github.com/denoland/deno/issues/1478#issuecomment-452996736), the CSP errors should have been fixed now.

Maybe uncommenting [this line](https://github.com/dino-dna/denolandia/blob/cef6bf0f56c26782a5eeaf63906337b1fcdf9ead/packages/api/src/middleware/helmet.ts#L25) will fix it, or is it something else?

A new deploy will also add this [recent changes](https://github.com/dino-dna/denolandia/pull/1)!

**Comment by cdaringe** [comment]
greetings!  thanks.  in fact, the search bar isn't wired in at all yet. whoops!  the search _used_ to work when i exposed the default react table headers.  i didn't proceed much further on this yet because the deno team didn't give me any feedback to date.

- [this input](https://github.com/dino-dna/denolandia/blob/cef6bf0f56c26782a5eeaf63906337b1fcdf9ead/packages/ui/src/components/App.tsx#L18) needs an onChange handler, to update...
- [this react-table controlled state](https://github.com/dino-dna/denolandia/blob/cef6bf0f56c26782a5eeaf63906337b1fcdf9ead/packages/ui/src/components/SearchResults.tsx#L43)

it's not super pretty, but i'm keen on letting react-table do all of the heavy lifting of managing all of the table state.

**Comment by cdaringe** [comment]
![](https://user-images.githubusercontent.com/1003261/50815568-6e089880-12d2-11e9-95af-3f5e9a479899.png)

the little input below the "Package" header _actually_ works, but i hid it in favor of using the giant banner search input.  just didn't pass it on thru

**Comment by leonardodino** [comment]
_whoops_, my bad also, didn't had the time to read through much of the code.

I saw that you removed the `react-table` header, but assumed that the search wasn't working because of the error in the console. Now it makes sense.

Yeah, agreed, when opting into a self-managed component does make the rest of the code simpler.

**update**: you may close this off, or open another dedicated to implementing the search, your call.
Right now, I'm little tough on time, wish could help more.

**Comment by leonardodino** [comment]
closing this, everything is fixed :tada: thanks!
